name: sisfo_sarpras
description: A Flutter app connected to Laravel API

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/bg_login.png
